exec-once = /nix/store/2hc6lqclam28wdnjgd8gjdmw168mlf1a-dbus-1.16.2/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
bind=SUPER, Q, exec, kitty
bind=SUPER, B, exec, firefox
bind=SUPER, E, exec, kitty -e yazi
bind=SUPER, C, killactive,
bind=SUPER, M, exec, /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call shell open power
bind=SUPER, V, togglefloating,
bind=SUPER, F, fullscreen,
bind=SUPER, L, exec, pidof hyprlock || hyprlock
bind=SUPER, SPACE, exec, /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call shell launcher all
bind=SUPER, R, exec, /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call shell launcher apps
bind=SUPER, X, exec, /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call shell toggle power
bind=SUPER, W, killactive,
bind=SUPER CTRL, N, exec, /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call shell toggle network
bind=SUPER CTRL, A, exec, /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call shell toggle agents
bind=SUPER CTRL, T, exec, /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call shell toggle themes
bind=SUPER CTRL, D, exec, /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call shell dnd
bind=SUPER CTRL, P, exec, /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call shell toggle predator
bind=SUPER SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
bind=, Print, exec, grim -g "$(slurp)" - | wl-copy
bind=SUPER, left, movefocus, l
bind=SUPER, right, movefocus, r
bind=SUPER, up, movefocus, u
bind=SUPER, down, movefocus, d
bind=SUPER, 1, workspace, 1
bind=SUPER SHIFT, 1, movetoworkspace, 1
bind=SUPER, 2, workspace, 2
bind=SUPER SHIFT, 2, movetoworkspace, 2
bind=SUPER, 3, workspace, 3
bind=SUPER SHIFT, 3, movetoworkspace, 3
bind=SUPER, 4, workspace, 4
bind=SUPER SHIFT, 4, movetoworkspace, 4
bind=SUPER, 5, workspace, 5
bind=SUPER SHIFT, 5, movetoworkspace, 5
bind=SUPER, 6, workspace, 6
bind=SUPER SHIFT, 6, movetoworkspace, 6
bind=SUPER, 7, workspace, 7
bind=SUPER SHIFT, 7, movetoworkspace, 7
bind=SUPER, 8, workspace, 8
bind=SUPER SHIFT, 8, movetoworkspace, 8
bind=SUPER, 9, workspace, 9
bind=SUPER SHIFT, 9, movetoworkspace, 9

bindel=, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel=, XF86MonBrightnessUp, exec, brightnessctl -q s 5%+ && /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call osd brightness
bindel=, XF86MonBrightnessDown, exec, brightnessctl -q s 5%- && /nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs ipc -c sumi call osd brightness

bindl=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl=, XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl=, XF86AudioPlay, exec, playerctl play-pause
bindl=, XF86AudioNext, exec, playerctl next
bindl=, XF86AudioPrev, exec, playerctl previous

bindm=SUPER, mouse:272, movewindow
bindm=SUPER, mouse:273, resizewindow

exec-once=sumi-theme --restore
exec-once=/nix/store/3v0czgvmyms467pk4cbd3qx52qli1jbq-quickshell-0.3.0/bin/qs -c sumi

general {
  border_size=2
}
